name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Production)
        uses: vercel/actions@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          org-id: folkodegroups-projects
          project-id: landing-kbah34ym7
          github-comment: true
        env:
          VERCEL_TELEMETRY_DISABLED: 1
          NEXT_TELEMETRY_DISABLED: 1

  vercel-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Preview)
        uses: vercel/actions@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          org-id: folkodegroups-projects
          project-id: landing-kbah34ym7
          github-comment: true
        env:
          VERCEL_TELEMETRY_DISABLED: 1
          NEXT_TELEMETRY_DISABLED: 1