name: PR Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          CI: true
