name: Vercel Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop # Para PRs de features/X a develop
      - main    # Para PRs de develop a main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel Preview
        uses: BetaHuhn/deploy-to-vercel-action@v4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}